## Memory Efficiency of NumPy

In [332]:
import numpy as np

li_arr = [i for i in range(100)]
np_arr = np.arange(100)

print(li_arr)
print()
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [333]:
## Size of one element in numpy array
print(np_arr.itemsize)

## Size of 100 elements in numpy array
print(np_arr.itemsize * np_arr.size)

8
800


In [334]:
import sys

## Size of one element in list
a = 10
print(sys.getsizeof(a))

## Size of 100 elements in list
print(sys.getsizeof(1) * len(li_arr))

28
2800


## Execution Time Efficiency of NumPy

In [220]:
import time
import numpy as np

size = 100000

## Add elements of array a and b

def addition_using_list():
    t1 = time.time()
    a = range(size)
    b = range(size)
    c = [a[i]+b[i] for i in range(size)]
    t2 = time.time()
    return (t2 - t1)

def addition_using_numpy():
    t1 = time.time()
    a = np.arange(size)
    b = np.arange(size)
    c = a + b
    t2 = time.time()
    return (t2- t1)

t_list = addition_using_list()
t_numpy = addition_using_numpy()
print('Time taken in List  = ', t_list)
print('Time taken in nparr = ', t_numpy)

Time taken in List  =  0.051204681396484375
Time taken in nparr =  0.0016837120056152344


## Create NumPy Array

In [221]:
import numpy as np

In [222]:
a = [1, 2, 3, 4, 5]
b = np.array(a)
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [223]:
a = [1, 2, 3, 4, 5, '6', '7', 8.3]
b = np.array(a)
print(b)
print(type(b))

['1' '2' '3' '4' '5' '6' '7' '8.3']
<class 'numpy.ndarray'>


In [224]:
a = [1, 2, 3, 4, 5, '6', '7', 8.3]
b = np.array(a, dtype = str)
print(b)
print(type(b))

['1' '2' '3' '4' '5' '6' '7' '8.3']
<class 'numpy.ndarray'>


In [225]:
a = [1, 2, 3, 4, 5, '6', '7', 8.3]
b = np.array(a, dtype = int)
print(b)
print(type(b))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [226]:
a = [1, 2, 3, 4, 5, '6', '7', 8.3]
b = np.array(a, dtype = float)
print(b)
print(type(b))

[1.  2.  3.  4.  5.  6.  7.  8.3]
<class 'numpy.ndarray'>


In [227]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [228]:
b = np.zeros(3)
b

array([0., 0., 0.])

In [229]:
b = np.ones((2,3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [230]:
b = np.ones((3,2,4), dtype = int)
b

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [231]:
b.ndim

3

In [232]:
b = np.full(3, 4, dtype = float)
b

array([4., 4., 4.])

In [233]:
b = np.full((3,4), 5)
b

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [234]:
b = np.empty(5)
b

array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323])

In [235]:
arr = [[1,2,3], [4,5,6], [7,8,9]]
np_arr = np.array(arr)
np_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [236]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
b = np.arange(2, 10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [238]:
b = np.arange(2, 10, 2)
b

array([2, 4, 6, 8])

In [239]:
b = np.linspace(2, 10, 5)
print(b)
print(b[1]-b[0])
print(b[2]-b[1])
print(b[3]-b[2])

[ 2.  4.  6.  8. 10.]
2.0
2.0
2.0


In [240]:
b = np.random.rand(3)
b

array([0.39363162, 0.38469968, 0.37363765])

In [241]:
b = np.random.rand(3,4)
b

array([[0.58424786, 0.53183521, 0.11932995, 0.79221196],
       [0.12740867, 0.90705974, 0.83624911, 0.16288051],
       [0.9827181 , 0.72773862, 0.95083908, 0.57325033]])

In [242]:
b = np.random.rand(10) * 10
b

array([8.73426836, 5.29007334, 3.757607  , 5.88132653, 7.79320793,
       7.83985595, 8.73491069, 5.22508936, 3.54002264, 2.05938406])

In [243]:
b = np.random.randint(10, size = 4)
b

array([3, 1, 4, 4])

In [244]:
b = np.random.randint(10, size = (3,4))
b

array([[2, 2, 5, 1],
       [8, 2, 5, 0],
       [0, 2, 3, 4]])

In [245]:
b = np.random.randint(2, [5,7,9,10])
b

array([3, 2, 2, 9])

In [246]:
b = np.random.randint(2, [5,7,10])
b

array([2, 6, 9])

In [247]:
b = np.random.randint([2, 4, 6], [8, 15, 20])
b

array([ 7, 10, 10])

In [248]:
b = np.random.randint([2, 4, 6], [8, 15, 20])
b

array([ 4,  9, 11])

In [249]:
b = np.random.randint([1, 3, 5, 7], [[15], [20], [25], [30], [35]])
b

array([[ 3, 13, 11, 11],
       [15, 12, 15, 19],
       [ 3, 22, 22, 23],
       [18, 23, 22, 24],
       [ 5, 19,  5, 16]])

In [250]:
b = np.arange(9, 50)
b

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [251]:
b = np.eye(5,6)
b

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [252]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [253]:
li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [254]:
li_2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [255]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int64
(8,)


In [256]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int64
(32, 8)


In [257]:
arr[3]

4

In [258]:
arr[0:]

array([1, 2, 3, 4, 5])

In [259]:
arr[1:]

array([2, 3, 4, 5])

In [260]:
arr[3:]

array([4, 5])

In [261]:
arr_2d[2,3]

12

In [262]:
arr_2d[2][3]

12

In [263]:
arr_2d[1][:3]

array([5, 6, 7])

In [264]:
arr_2d[1, :3]

array([5, 6, 7])

In [265]:
print(arr_2d[:3, 3])

[ 4  8 12]


In [266]:
b = np.arange(0, 5, round(5/9, 2))
b

array([0.  , 0.56, 1.12, 1.68, 2.24, 2.8 , 3.36, 3.92, 4.48])

In [267]:
print(arr_2d[2:4, 1:3])

[[10 11]
 [14 15]]


In [268]:
li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[15  9 12 12  1]
[10 15 12 16 18]


In [269]:
li = [i+1 for i in li]

In [270]:
li

[2, 3, 4, 5, 6]

In [271]:
a = a + 1
a

array([16, 10, 13, 13,  2])

In [272]:
c = a + b
c

array([26, 25, 25, 29, 20])

In [273]:
d = a - b

In [274]:
d

array([  6,  -5,   1,  -3, -16])

In [275]:
e = a * b
e

array([160, 150, 156, 208,  36])

In [276]:
f = a / b
f

array([1.6       , 0.66666667, 1.08333333, 0.8125    , 0.11111111])

In [277]:
g = a // b
g

array([1, 0, 1, 0, 0])

In [278]:
h = a**b
h

array([     1099511627776,   1000000000000000,     23298085122481,
       665416609183179841,             262144])

In [279]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[16 10 13 13  2]
54
10.8
2
4
16
0


In [280]:
print(a)
print(b)

[16 10 13 13  2]
[10 15 12 16 18]


In [281]:
a > b

array([ True, False,  True, False, False])

In [282]:
a < b

array([False,  True, False,  True,  True])

In [283]:
a <= b

array([False,  True, False,  True,  True])

In [284]:
a >= b

array([ True, False,  True, False, False])

In [285]:
a == b

array([False, False, False, False, False])

In [286]:
a.all() or b.all()

True

In [287]:
a.all()

True

In [288]:
b.all()

True

In [289]:
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [290]:
print(np.logical_not(a))

[False False False False False]


In [291]:
print(np.logical_xor(a, b))

[False False False False False]


In [292]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [293]:
np.logical_not(a)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [294]:
b = np.array([[4, 3, 2, 1], [8, 7, 6, 5], [12, 11, 10, 9]])
b

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [295]:
a + b

array([[ 5,  5,  5,  5],
       [13, 13, 13, 13],
       [21, 21, 21, 21]])

In [296]:
np.logical_and(a, b)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [297]:
a[0,0] = 0
np.logical_and(a, b)

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [298]:
np.logical_or(a, b)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [299]:
np.logical_not(a)

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [300]:
np.logical_xor(a, b)

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### Boolean Indexing

In [301]:
a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 2 14  5 14  5 14  2 12]


In [302]:
print(b > 10)

[False  True False  True False  True False  True]


In [303]:
b

array([ 2, 14,  5, 14,  5, 14,  2, 12])

In [304]:
bool_arr = b > 10
bool_arr

array([False,  True, False,  True, False,  True, False,  True])

In [305]:
new_arr = b[bool_arr]
new_arr

array([14, 14, 14, 12])

In [306]:
new_arr = b[b > 10]
new_arr

array([14, 14, 14, 12])

In [307]:
b[(b > 10) & (b < 18)]

array([14, 14, 14, 12])

In [308]:
print(b)

[ 2 14  5 14  5 14  2 12]


In [309]:
c = b
c

array([ 2, 14,  5, 14,  5, 14,  2, 12])

In [310]:
c[:3] = 19
c

array([19, 19, 19, 14,  5, 14,  2, 12])

In [311]:
c[c > 15] = 100
c

array([100, 100, 100,  14,   5,  14,   2,  12])

In [312]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100  14   5  14   2  12]


In [313]:
index = np.where(b == 100)
a[index]

array(['t', 'b', 'r'], dtype='<U1')

In [314]:
a = np.array([1, 2, 0, 0, 4, 0])
a

array([1, 2, 0, 0, 4, 0])

In [315]:
print(np.where(a != 0))

(array([0, 1, 4]),)


In [316]:
a = np.array([1, 3, 5, 7, 9, 11, 13, 15, 19])
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 19])

In [317]:
np.where(a % 3 == 0)

(array([1, 4, 7]),)

In [318]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [319]:
print(a)
a[a&1 != 0] = -1
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [320]:
a = np.random.randint(1, 30, (5, 6))
a

array([[ 6,  3, 29, 20,  6, 18],
       [20,  8, 23, 16, 10,  5],
       [12, 10,  7, 27,  8, 29],
       [27, 25, 24, 12, 14, 20],
       [19,  5, 19, 26,  8,  4]])

In [321]:
bool_arr = a > 20
bool_arr

array([[False, False,  True, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False,  True],
       [ True,  True,  True, False, False, False],
       [False, False, False,  True, False, False]])

In [322]:
ans = a[bool_arr]
print(ans)

[29 23 27 29 27 25 24 26]


In [323]:
b = a
b

array([[ 6,  3, 29, 20,  6, 18],
       [20,  8, 23, 16, 10,  5],
       [12, 10,  7, 27,  8, 29],
       [27, 25, 24, 12, 14, 20],
       [19,  5, 19, 26,  8,  4]])

In [324]:
b[bool_arr] = 100
b

array([[  6,   3, 100,  20,   6,  18],
       [ 20,   8, 100,  16,  10,   5],
       [ 12,  10,   7, 100,   8, 100],
       [100, 100, 100,  12,  14,  20],
       [ 19,   5,  19, 100,   8,   4]])

In [325]:
bool_arr = b[:, 3] == 100
print(bool_arr)

[False False  True False  True]


In [326]:
print(b[:, 3])
b[bool_arr, 3] = 99
print(b[:, 3])

[ 20  16 100  12 100]
[20 16 99 12 99]


In [327]:
b

array([[  6,   3, 100,  20,   6,  18],
       [ 20,   8, 100,  16,  10,   5],
       [ 12,  10,   7,  99,   8, 100],
       [100, 100, 100,  12,  14,  20],
       [ 19,   5,  19,  99,   8,   4]])

In [328]:
a

array([[  6,   3, 100,  20,   6,  18],
       [ 20,   8, 100,  16,  10,   5],
       [ 12,  10,   7,  99,   8, 100],
       [100, 100, 100,  12,  14,  20],
       [ 19,   5,  19,  99,   8,   4]])

In [329]:
b

array([[  6,   3, 100,  20,   6,  18],
       [ 20,   8, 100,  16,  10,   5],
       [ 12,  10,   7,  99,   8, 100],
       [100, 100, 100,  12,  14,  20],
       [ 19,   5,  19,  99,   8,   4]])

In [331]:
b[0,1] = 10
a

array([[  6,  10, 100,  20,   6,  18],
       [ 20,   8, 100,  16,  10,   5],
       [ 12,  10,   7,  99,   8, 100],
       [100, 100, 100,  12,  14,  20],
       [ 19,   5,  19,  99,   8,   4]])

### Broadcasting in NumPy Array

In [335]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))

In [339]:
print(x)
print()
print(y)

[[8 5 6]
 [7 6 2]
 [1 9 4]]

[[3 2 3]
 [6 1 6]
 [7 8 9]]


In [340]:
ans = x - y
ans

array([[ 5,  3,  3],
       [ 1,  5, -4],
       [-6,  1, -5]])

In [341]:
ans = x + y
ans

array([[11,  7,  9],
       [13,  7,  8],
       [ 8, 17, 13]])

In [342]:
ans = x * y
ans

array([[24, 10, 18],
       [42,  6, 12],
       [ 7, 72, 36]])

In [343]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, 3)
print(x)
print(y)

[[9 3 7]
 [4 2 7]
 [4 7 6]]
[2 7 3]


In [344]:
ans = x - y
ans

array([[ 7, -4,  4],
       [ 2, -5,  4],
       [ 2,  0,  3]])

In [345]:
ans = x + y
ans

array([[11, 10, 10],
       [ 6,  9, 10],
       [ 6, 14,  9]])

In [346]:
ans = x * y
ans

array([[18, 21, 21],
       [ 8, 14, 21],
       [ 8, 49, 18]])

In [347]:
a = np.random.randint(1, 10, (2,3))
a

array([[1, 8, 7],
       [9, 7, 5]])

In [348]:
b = np.transpose(a)
b

array([[1, 9],
       [8, 7],
       [7, 5]])

#### resize() and reshape()

In [349]:
a

array([[1, 8, 7],
       [9, 7, 5]])

In [354]:
b

array([[1, 9],
       [8, 7],
       [7, 5]])

In [355]:
a.shape

(2, 3)

In [356]:
b.shape

(3, 2)

In [357]:
c = a.reshape(3, 2)
c

array([[1, 8],
       [7, 9],
       [7, 5]])

In [358]:
a

array([[1, 8, 7],
       [9, 7, 5]])

In [359]:
c

array([[1, 8],
       [7, 9],
       [7, 5]])

In [360]:
a.resize(3, 2)
a

array([[1, 8],
       [7, 9],
       [7, 5]])